name: Build docker image kicad6_and_pandoc

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '42 3 5 * *'
    # Monthly automated rebuild / "At 03:42 on day-of-month 5"

jobs:
  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Generate date/version string
        run: |
         export VERSION_TMP="$(date +%F)"
         echo $VERSION_TMP
         echo "VERSION=$VERSION_TMP" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push kicad6_and_pandoc
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./kicad6_and_pandoc.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rleh/kicad6_and_pandoc:${{ env.VERSION }}
            ghcr.io/rleh/kicad6_and_pandoc:latest
